version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
    - echo installing maven...
    - apt-get update -y
    - apt-get install -y maven
  pre_build:
    commands:
      -  java -version
  build:
    commands:
      - echo Build started on `date`
      - cd src &&  mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
  - '/root/.m2/**/*'