version: 0.2


phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      -  java -version
  build:
    commands:
      - echo Build started on `date`
      - cd src &&  mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: no
cache:
  paths:
  - '/root/.m2/**/*'
